FROM python:3.13-slim as base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update -y \
    && apt-get install -y build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools uvicorn httpx fastapi pydantic

WORKDIR /app

COPY ./tests/providers ./

FROM base as silpo

EXPOSE 8000/tcp
ENTRYPOINT [ "python" ]
CMD [ "-m", "uvicorn", "silpo:app", "host", "0.0.0.0" ]

FROM base as kfc

EXPOSE 8000/tcp
ENTRYPOINT [ "python" ]
CMD [ "-m", "uvicorn", "kfc:app", "host", "0.0.0.0" ]

FROM base as uklon

EXPOSE 8000/tcp
ENTRYPOINT [ "python" ]
CMD [ "-m", "uvicorn", "uklon:app", "host", "0.0.0.0" ]